fix: more fixes to faulty IPCA handling
inco-org/fincore pull request #10
Opened 2024-12-11 12:30 UTC by viotti

2024-12-11 12:34 UTC, viotti commented
![](https://github.trello.services/images/mini-trello-icon.png) [Corrigir e testar cronograma IPCA Max Tulum](https://trello.com/c/Ud8xmnZu/3002-corrigir-e-testar-cronograma-ipca-max-tulum)

2024-12-12 18:34 UTC, gzillepv requested changes

2024-12-12 18:34 UTC, gzillepv commented on labs/fincore-01.ipynb
> +        "FC &= (1 + \\frac{VM_k}{100})^\\frac{dp}{dt} \\\\\n",
Não vai considerar que é um produtório mais? Para representar a agregação das variações do período.

2024-12-15 21:45 UTC, viotti commented on labs/fincore-01.ipynb
> +        "FC &= (1 + \\frac{VM_k}{100})^\\frac{dp}{dt} \\\\\n",
Não sei se você viu, mas transformei a parte de IPCA JM em duas seções:

* Indexador ICPA (Corrigido Mensalmente)
* Indexador ICPA (Correção na Última Prestação)

No caso da seção **Indexador ICPA (Corrigido Mensalmente)**, não é um produtório. É sempre a variação do mês M-2 do pagamento.

Mas para a seção **Indexador ICPA (Correção na Última Prestação)**, permanece sendo o produtório das variações mensais do período de n meses começando em M-2 do primeiro pagamento.

O **diff** do caderno do Jupyter é ruim de ler mesmo…

2024-12-17 18:15 UTC, merged