feat: injecting regs into payment object
inco-org/fincore pull request #9
Opened 2024-11-08 18:36 UTC by gzillepv

2024-11-08 19:56 UTC, viotti commented
@gzillepv outra coisa, chama de `_regs`.

2024-11-11 12:14 UTC, viotti requested changes
Incrementa a versão minor no `setup.py`.

2024-11-11 18:15 UTC, viotti requested changes

2024-11-11 18:15 UTC, viotti commented on setup.py
> +    version='4.1.2',
```suggestion
    version='4.1.0',
```

2024-11-11 18:31 UTC, gzillepv commented on setup.py
> +    version='4.1.2',
Vacilo, malz.

2024-11-11 18:35 UTC, viotti approved these changes

2024-11-11 18:35 UTC, merged